### ISSUE TITLE
Camera Attributes & Animation Window Home Graph Bug

### ISSUE THREAD

**Issue by jholmes09** [EnviralDesign/GeoPix#26]
**Describe the bug**
Two Part Issue:

1) The General Tx/Ty/Tz attributes are almost always over the slider's limit of 1000, resulting in difficult scroll-wheel or slider manipulation.

2) The Animation Editor defaults to a view window range of 0-1 which is inpractical for any of the T or R general attributes. While you can zoom out to find your camera keyframes, there does not appear to be a way to zoom into anything other than 0-1, effectively making the window unusable. Home Graph Button defaults back to 0-1.

**To Reproduce**
1. Set Camera Position
2. Right Click Rx to set Keyframe
3. Move timeline 
4. Change Rx value
5. Right Click to set Keyframe
6. Click Animation Editor
7. Notice Animation Editor is defaulting to 0-1 range in window.
8. Scroll out till you find the keyframes you just created
9. Attempt to edit (won't work)
10. Attempt to zoom into that range
11. Press Home Graph Camera (H), it defaults to 0-1

**Expected behavior**
General Camera Parameters should not have a slider limit at all.
Animation Window should automatically adjust its range/scale to typical parameter range and be able to zoom into any portion of the window desired.

**Screenshots**
![image](https://user-images.githubusercontent.com/18503894/120221100-ce823280-c20b-11eb-8633-77f36dcae608.png)

![image](https://user-images.githubusercontent.com/18503894/120221133-db9f2180-c20b-11eb-852a-7d2f2f83e24b.png)

**Desktop (please complete the following information):**
Windows 10
AMD Ryzen with Vega 11 Graphics
4K Monitor

**Comment by EnviralDesign** [comment]
Hey @jholmes09 - welcome!

Issues with the animation editor have been fixed. Thanks for reporting that.

As far as the attribute bounds, the way the UI is built out across the software, numeric parameters must have a low and high end, even if that param type doesn't really benefit from that specific range. It's intended to mirror how custom parameters are built out in TouchDesigner.

Have you tried using the ctrl modifiers for scroll adjusting those parameters that are too sensitive? The scroll adjust function also should not stop at a specific value unless it's supposed to be clamped.

So, for camera position for instance, there is a soft range, but not a hard range. for other things there is a hard range that is enforced.

I can also make the range for specific parameters of specific object types larger or smaller if that makes more logical sense.

**Comment by jholmes09** [comment]
Thank you! I will try that!

**Comment by jholmes09** [comment]
Hey I must be doing something wrong with the animation window. Your fixes work but I cannot seem to get any of the other buttons to do anything (select, add key frames, etc). Is there a special hotkey I need to push first?

**Comment by EnviralDesign** [comment]
@jholmes09 ya I think it's probably because there's no animation channels in there to work with? or have you already made some?

Try the following and let me know if this works for you or if there's maybe a bug somewhere for you I'm not seeing:
1) create a primitive cube
2) right click on Ry value, and set keyframe (at frame 1)
3) drag timeslider at bottom to frame ~100
4) keyframe Ry again
5) in animation editor, you should have a tile on the left, that says object/Primitive1/Ry, or something similar. select that
6) Click the home button in the top of the animation editor, should home to the two keyframes being visible.
7) click on the add keyframes tool (A for hotkey if needed)
8) click somewhere between the two keyframes, a middle one should appear
9) go to select mode, then try moving that newly selected keyframe around
10) try the other buttons in the animation editor, and see if they work as well.

for me I was able to get through this process but let me know if you see any errors pop up!

**Comment by EnviralDesign** [comment]
also do the above with the latest pull, lots has been changing there lately.
