### ISSUE TITLE
Not Getting GeoPix menu

### ISSUE THREAD

**Issue by cojosass** [EnviralDesign/GeoPix#7]
**Describe the bug**
I downloaded the zip file and extracted it to my desktop. When I try to open the GeoPix_2.0 file I get the message "Error loading network. File may be truncated." This also just opens a touchdesigner file and not the geopix screen. I get the same error when trying the unextracted zip file in my downloads.

**To Reproduce**
1. GeoPix-main
2. GP
3. GeoPix_2.0

**Expected behavior**
The GeoPix menu screen to open.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by EnviralDesign** [comment]
Did you download the zip file from the code download button?
If so, try downloading the releases package instead and let me know if that works for you.

GitHub is currently undergoing some unexpected maintenance related to file size so that's the goto for now until it's sorted.

![image](https://user-images.githubusercontent.com/10091486/114236362-1e98f300-9947-11eb-8e59-cca7d29b74b4.png)

**Comment by EnviralDesign** [comment]
You can also download via the GitHub client, and that should work but the green zip download button specifically is not working for a little while.

**Comment by cojosass** [comment]
It works now, I used the initial release

**Comment by EnviralDesign** [comment]
great! will have the repo download button fixed soon enough. thanks for the detailed report
